services:
  - type: web
    name: portfolio-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: FLASK_ENV
        value: production
region: oregon